[2024-11-28T13:06:32.816+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_split_google_sheets.upload_to_google_sheets manual__2024-11-28T13:01:24.969402+00:00 [queued]>
[2024-11-28T13:06:32.824+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_split_google_sheets.upload_to_google_sheets manual__2024-11-28T13:01:24.969402+00:00 [queued]>
[2024-11-28T13:06:32.824+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T13:06:32.825+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-11-28T13:06:32.825+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T13:06:32.837+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): upload_to_google_sheets> on 2024-11-28 13:01:24.969402+00:00
[2024-11-28T13:06:32.846+0000] {standard_task_runner.py:55} INFO - Started process 109 to run task
[2024-11-28T13:06:32.848+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_split_google_sheets', 'upload_to_google_sheets', 'manual__2024-11-28T13:01:24.969402+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/data_processing_dag.py', '--cfg-path', '/tmp/tmpxs_0a_rl']
[2024-11-28T13:06:32.850+0000] {standard_task_runner.py:83} INFO - Job 91: Subtask upload_to_google_sheets
[2024-11-28T13:06:32.909+0000] {task_command.py:388} INFO - Running <TaskInstance: data_split_google_sheets.upload_to_google_sheets manual__2024-11-28T13:01:24.969402+00:00 [running]> on host a1ef49675f1c
[2024-11-28T13:06:32.966+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_split_google_sheets
AIRFLOW_CTX_TASK_ID=upload_to_google_sheets
AIRFLOW_CTX_EXECUTION_DATE=2024-11-28T13:01:24.969402+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-28T13:01:24.969402+00:00
[2024-11-28T13:06:33.023+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_processing_dag.py", line 69, in upload_to_google_sheets
    train = pd.read_json(train_data_json)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 733, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 818, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 858, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 713, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 451, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2024-11-28T13:06:33.032+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=data_split_google_sheets, task_id=upload_to_google_sheets, execution_date=20241128T130124, start_date=20241128T130632, end_date=20241128T130633
[2024-11-28T13:06:33.045+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 91 for task upload_to_google_sheets (Invalid file path or buffer object type: <class 'NoneType'>; 109)
[2024-11-28T13:06:33.062+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-28T13:06:33.075+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
